config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
      resources :users
      resources :about_contents
      resources :business_details
      resources :extra_pages
      resources :integrations
      resources :services_contents
      resources :uploads
      resources :attachments
      resources :blobs

      root to: "users#index"
    end
  resources :services_contents, only: [:update, :edit, :show]
  resources :extra_pages, only: [:update, :edit, :show]
  resources :uploads, only: [:update, :edit, :show]
  resources :about_contents, only: [:update, :edit, :show]
  resources :integrations, only: [:update, :edit, :show]
  resources :business_details, only: [:update, :edit, :show]
  resources :users, only: [:update, :destroy]
  authenticated :user do
    root to: "pages#dashboard"
  end
  unauthenticated :user do
    root "pages#index"
  end
  
  get 'dashboard', to: "pages#dashboard"
  get 'pages/about'
  get 'pages/index'
  get 'pages/contact'
  get 'pages/reviews'
  get 'pages/pricing'
  get 'pages/basic'
  get 'pages/fancy'
  get 'pages/custom'
  get 'pages/why-we-hand-code', to: "pages#why_we_hand_code"
  get 'pages/keeping-prices-down', to: "pages#keeping_prices_down"
  get 'pages/referral-program', to: "pages#free_beer"
  get 'pages/free-beer'
  get 'freebeer', to: "pages#free_beer"
  devise_for :users
end

app/views/layouts/navigation/sidebar/_sidebar.html.erb
<ul class="nav single-location">
  <% if user_signed_in? %>
    <div class="divider text-center" data-content="Hey there <%= current_user.name %>! 👋"></div>
    <% if is_complete? && current_user.is_submitted %>
      <li class="nav-item btn btn-primary">
        <%= link_to dashboard_path do  %>
          <i class="icon icon-check"></i>  Submitted!
          <% end %>
      </li>
    <% elsif is_complete? %>
      <li class="nav-item btn btn-primary">
        <%= link_to dashboard_path do  %>
          <i class="icon icon-check"></i>  Ready To Submit
          <% end %>
      </li>
    <% else %>
      <li class="nav-item btn btn-primary">
        <%= link_to dashboard_path do  %>
          <i class="icon icon-time"></i>  Submission Status
          <% end %>
      </li>
    <% end %>
    <%= render 'layouts/navigation/sidebar/nav_items/contact_info' %>
    <%= render 'layouts/navigation/sidebar/nav_items/website_content' %>
    <%= render 'layouts/navigation/sidebar/nav_items/service_pricing' %>
    <%= render 'layouts/navigation/sidebar/nav_items/integration' %>
    <%= render 'layouts/navigation/sidebar/nav_items/uploads' %>
    <%= render 'layouts/navigation/sidebar/nav_items/extra_pages' %>
  <% end %>  
</ul>