config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
      resources :users
      resources :about_contents
      resources :business_details
      resources :extra_pages
      resources :integrations
      resources :services_contents
      resources :uploads
      resources :attachments
      resources :blobs

      root to: "users#index"
    end
  resources :services_contents, only: [:update, :edit, :show]
  resources :extra_pages, only: [:update, :edit, :show]
  resources :uploads, only: [:update, :edit, :show]
  resources :about_contents, only: [:update, :edit, :show]
  resources :integrations, only: [:update, :edit, :show]
  resources :business_details, only: [:update, :edit, :show]
  resources :users, only: [:update, :destroy]
  authenticated :user do
    root to: "pages#dashboard"
  end
  unauthenticated :user do
    root "pages#index"
  end
  
  get 'dashboard', to: "pages#dashboard"
  get 'pages/about'
  get 'pages/index'
  get 'pages/contact'
  get 'pages/reviews'
  get 'pages/pricing'
  get 'pages/basic'
  get 'pages/fancy'
  get 'pages/custom'
  get 'pages/why-we-hand-code', to: "pages#why_we_hand_code"
  get 'pages/keeping-prices-down', to: "pages#keeping_prices_down"
  get 'pages/referral-program', to: "pages#free_beer"
  get 'pages/free-beer'
  get 'freebeer', to: "pages#free_beer"
  devise_for :users
end

app/views/layouts/footer/_pages_footer.html.erb
<div class="container">
  <div class="columns">
    <div class="column col-sm-12 show-sm center">
      <div class="footer-brand">
          <%= image_tag 'nobull_logo_white.svg', class: 'img-responsive', alt: ''%>
      </div>
      <p class="text-center  mx-10 mt-4">
        NoBull Software Co. is a small, family-owned web development company based in both
        Salmon Arm, BC and Calgary, AB - both of which are in the beautiful country of Canada. 🇨🇦
      </p>
      <p class="text-center  mx-10">
        All prices listed on this site are in $CAD.
      </p>
      <p class="text-center mx-10">Thanks for dropping by! 😊</p>
    </div>
    
    <div class="column col-4 col-sm-12 left">
     <ul class="nav footer-nav">
       <li class="nav-item">
        <%= link_to 'Home', root_path %>
       </li>
       <li class="nav-item">
        <%= link_to 'Our Story', pages_about_path %>
       </li>
       <li class="nav-item">
        <%= link_to 'Contact Us', pages_contact_path %>
       </li>
       <li class="nav-item">
        <%= link_to 'Services & Pricing', pages_pricing_path %>
       </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Request New Site', new_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Free Beer', pages_free_beer_path %>
        </li>
     </ul>
    </div>
    <div class="column col-4 col-sm-12 hide-sm center">
      <%= link_to root_path do %>
        <div class="footer-brand">
          <%= image_tag 'nobull_logo_white.svg', class: 'img-responsive', alt: ''%>
        </div>
      <% end %>
      <p class="text-center  mx-10 mt-4">
        NoBull Software Co. is a small, family-owned web development company focused
        on selling only things we're proud of, at fair  and upfront prices.
        <%= I18n.t :footer_based_from %>
        <br>Thanks for dropping by our site! 😊
      </p>
      <p class="text-center  mx-10">
        All prices listed on this site are in <strong><%= I18n.t :locale_currency_used %></strong>
      </p>
    </div>
    <div class="column col-4 col-sm-12 right">
      <div class="social-nav">
        <%= link_to "#{I18n.t(:footer_chat_link)}", class: 'social-link' do %>
          <span class="social-text" id="after-span-phone"> Message us on <%= I18n.t :footer_chat_name %></span> 
          <%= image_tag "#{I18n.t(:footer_chat_logo)}", class: ' social-icon' %>
        <% end %>
        <%= link_to 'mailto:contact@nobullco.com', class: 'social-link' do %>
          <span class="social-text">Email</span> 
          <%= image_tag 'email_logo.svg', class: ' social-icon' %>
        <% end %>
        <%= link_to "tel:#{I18n.t(:link_phone)}", class: 'social-link' do %>
          <span class="social-text" id="after-span-phone"> <%= I18n.t :show_phone %></span> 
          <%= image_tag 'phone_logo.svg', class: ' social-icon' %>
        <% end %>
        <%= link_to 'https://twitter.com/richjdsmith', class: 'social-link' do %>
          <span class="social-text">Twitter</span> 
          <%= image_tag 'twitter_logo.svg', class: ' social-icon' %>
        <% end %>
        <%= link_to 'https://www.facebook.com/nobullco', class: 'social-link' do %>
          <span class="social-text">Facebook</span> 
          <%= image_tag 'fb_logo.svg', class: ' social-icon' %>
        <% end %>
        <%= link_to 'https://linkedin.com/company/nobullco', class: 'social-link' do %>
          <span class="social-text">LinkedIn</span> 
          <%= image_tag 'li_logo.svg', class: ' social-icon' %>
        <% end %>
      </div>
    </div>
    
  </div>
  <span class="text-center is-centered footer-I18n">You're currently seeing the <strong><%= I18n.t :current_locale %></strong> version of our site. You can change that here:</span>
  <span class="text-center is-centered footer-I18n"><%= link_to '🇬🇧 - UK', url_for(locale: :gb) %> | <%= link_to '🏔🇨🇦 - BC', url_for(locale: :british_columbia) %> | <%= link_to '🤠🇨🇦 - Alberta', url_for(locale: :alberta) %> | <%= link_to '🌎 - The World', url_for(locale: :en) %></span>
  <span class="text-center is-centered" id="footer-copyright">Copyright <%= "#{Time.now.year}" %> - NoBull Software Co. </span>


</div>