config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :admin do
      resources :users
      resources :about_contents
      resources :business_details
      resources :extra_pages
      resources :integrations
      resources :services_contents
      resources :uploads
      resources :attachments
      resources :blobs

      root to: "users#index"
    end
  resources :services_contents, only: [:update, :edit, :show]
  resources :extra_pages, only: [:update, :edit, :show]
  resources :uploads, only: [:update, :edit, :show]
  resources :about_contents, only: [:update, :edit, :show]
  resources :integrations, only: [:update, :edit, :show]
  resources :business_details, only: [:update, :edit, :show]
  resources :users, only: [:update, :destroy]
  authenticated :user do
    root to: "pages#dashboard"
  end
  unauthenticated :user do
    root "pages#index"
  end
  
  get 'dashboard', to: "pages#dashboard"
  get 'pages/about'
  get 'pages/index'
  get 'pages/contact'
  get 'pages/reviews'
  get 'pages/pricing'
  get 'pages/basic'
  get 'pages/fancy'
  get 'pages/custom'
  get 'pages/why-we-hand-code', to: "pages#why_we_hand_code"
  get 'pages/keeping-prices-down', to: "pages#keeping_prices_down"
  get 'pages/referral-program', to: "pages#free_beer"
  get 'pages/free-beer'
  get 'freebeer', to: "pages#free_beer"
  devise_for :users
end

app/views/pages/dashboard/_about_contents.html.erb
<div class="row column col-12 columns no-margin-offset">
  <div class="column col-12">
    <h3 class="h5 title is-flex-centered">Website Content</h3>
    <p class=" subtitle is-flex-centered">
      This is the actual "stuff" that will be on your website. It'll either be shown on the homepage or possibly on an About Us Page. Things such as a bit of your businesses 
      history, your team or whatever else you want people to know about your business. 
    </p>
  </div>
  <div class="column col-12">
    <div class="columns">
      <% if current_user.about_contents_complete? %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-centered">
            Status: <span class="complete">Complete ✅</span>
          </div>
        </div>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link is-centered">
            <%= link_to about_content_path(current_user.about_content) do %>
              <i class="icon icon-more-vert"></i> See Submitted Content
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-flex-centered">
            Status: <span class="in-progress">Needs work</span> 🚧
          </div>  
        </div>  
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to edit_about_content_path(current_user.about_content) do %>
              <i class="icon icon-edit"></i> Fill Out Website Content
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>  

app/views/pages/dashboard/_business_details.html.erb
<div class="row column col-12 columns no-margin-offset">
            <div class="column col-12">
              <h3 class="h5 title is-flex-centered">Contact Info</h3>
              <p class=" subtitle is-flex-centered">
                This is where you give me all the contact information about your
                business. It's pretty important stuff - it'll be used to help people 
                to get in touch with you!
              </p>
            </div>
            <div class="column col-12">
              <div class="columns">
                <% if current_user.business_details_complete? %>
                  <div class="column col-5 col-md-12 col-mx-auto">
                    <div class="status is-centered">
                      Status: <span class="complete">Complete ✅</span>
                    </div>
                  </div>
                  <div class="column col-5 col-md-12 col-mx-auto">
                    <div class="row-link">
                      <%= link_to business_detail_path(current_user.business_detail) do %>
                        <i class="icon icon-more-vert"></i> See Contact Info
                      <% end %>
                    </div>
                  </div>
                <% else %>
                  <div class="column col-5 col-md-12 col-mx-auto">
                    <div class="status is-flex-centered">
                      Status: <span class="in-progress">Needs work</span> 🚧
                    </div>  
                  </div>  
                  <div class="column col-5 col-md-12 col-mx-auto">
                    <div class="row-link">
                      <%= link_to edit_business_detail_path(current_user.business_detail) do %>
                        <i class="icon icon-edit"></i> Fill out Contact Info
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>  

app/views/pages/dashboard/_extra_pages.erb
<div class="row column col-12 columns no-margin-offset">
  <div class="column col-12">
    <h3 class="h5 title is-flex-centered">Extra Pages</h3>
    <p class=" subtitle is-flex-centered">
      This is the place you can add extra pages if need more than the three your site comes with. It has already been marked as complete because honestly, you probably don't need any extra pages. Good job! You did one! 🙌
    </p>
  </div>
  <div class="column col-12">
    <div class="columns">
      <% if current_user.extra_pages_complete? %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-centered mb-1">
            Status: <span class="complete">Complete ✅</span>
          </div>
          <p class="text-center">(Not required - Totally Optional)</p>
        </div>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to extra_page_path(current_user.extra_page) do %>
              <i class="icon icon-more-vert"></i> See Extra Pages
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-flex-centered">
            Status: <span class="in-progress">Needs work</span> 🚧
          </div>  
        </div>  
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to edit_extra_page_path(current_user.extra_page) do %>
              <i class="icon icon-edit"></i>Add Pages
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>  

app/views/pages/dashboard/_integrations.html.erb
<div class="row column col-12 columns no-margin-offset">
  <div class="column col-12">
    <h3 class="h5 title is-flex-centered">Integrations</h3>
    <p class=" subtitle is-flex-centered">
      I'll use this provided information to add meta-data 
      (header tags and the likes - stuff Google likes to see which ranks websites that have it higher) and social sites to your new site. I'll also go through and make 
      sure all the data is the same across all the sites you provide me - something else Google and other search engines like to see. 
    </p>
  </div>
  <div class="column col-12">
    <div class="columns">
      <% if current_user.integrations_complete? %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-centered">
            Status: <span class="complete">Complete ✅</span>
          </div>
        </div>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to integration_path(current_user.integration) do %>
              <i class="icon icon-edit"></i> See Provided Integrations
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-flex-centered">
            Status: <span class="in-progress">Needs work</span> 🚧
          </div>  
        </div>  
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to edit_integration_path(current_user.integration) do %>
              <i class="icon icon-edit"></i> Fill Out Integration Data
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>  

app/views/pages/dashboard/_services_contents.html.erb
<div class="row column col-12 columns no-margin-offset">
  <div class="column col-12">
    <h3 class="h5 title is-flex-centered">Services & Pricing Content</h3>
    <p class=" subtitle is-flex-centered">
      This will be used on your "Pricing" or "Services" page (depending on what you submit). It will be used
      by your soon-to-be-customers™ (that just found your snazzy new site) to decide if you're the right fit for them.
    </p>
  </div>
  <div class="column col-12">
    <div class="columns">
      <% if current_user.services_contents_complete? %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-centered">
            Status: <span class="complete">Complete ✅</span>
          </div>
        </div>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to services_content_path(current_user.services_content) do %>
              <i class="icon icon-more-vert"></i> See Pricing/Services
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-flex-centered">
            Status: <span class="in-progress">Needs work</span> 🚧
          </div>  
        </div>  
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to edit_services_content_path(current_user.services_content) do %>
              <i class="icon icon-edit"></i> Fill Out Pricing & Services
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>  

app/views/pages/dashboard/_submited.html.erb
  <p class=" subtitle">
    Looks like everything was submitted! That's awesome. That means it's rocketing through the 
    interwebs and on it's way to me. I'll be in touch shortly! Until then, go enjoy a beer or a cup of coffee - you deserve it.
  </p>
<div class="column col-12">
  <div class="columns">
    <div class="column col-10 col-mx-auto">
      <progress class="progress" value="100" max="100"></progress>
      <div class="is-flex-centered">
        <h3 class="h6">Current Progress: <strong>100%</strong></h3>
      </div>
    </div>
  </div>
</div> 
<button class="btn disabled is-centered" tabindex="-1">Website Submitted</button>

app/views/pages/dashboard/_submiter.html.erb
  <p class=" subtitle">
    Once everything everything is complete, you'll be able to press the big submit button below. That'll lock your application from further edits and send me (Rich, your friendly website developer) an email that you're ready to proceed!
  </p>
<div class="column col-12">
  <div class="columns">
    <div class="column col-10 col-mx-auto">
      <progress class="progress" value="<%= calc_completeness %>" max="100"></progress>
      <div class="text-center">
        <h3 class="h6">Current Progress: <strong><%= calc_completeness.round %>%</strong> </h3>
        <h3 class="h6 subtle"><%= nearly_done_message %></h3>
      </div>
    </div>
  </div>
</div> 



<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this business_detail from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :is_submitted, value: true %>

  <div class="mt-4">
    <% if is_complete? %>
      <p class="text-center">Great work! Looks like everything is ship shape! Once you hit submit, it'll lock everything up and send it to me so I can get started. Ready for this? 😸 </p>
      <div class="actions">
        <%= form.submit "Submit your site", class: 'btn btn-primary is-centered' %>
      </div>
    <% else %>
      <button class="btn disabled is-centered" tabindex="-1">Submit Your Site</button>
      <p class="text-center">You'll be able to submit it to me once everything is complete!
      <br> Having troubles? <%= link_to 'Get in touch', pages_contact_path %>.</p>
    <% end %>
  </div>
<% end %>

app/views/pages/dashboard/_uploads.html.erb
<div class="row column col-12 columns no-margin-offset">
  <div class="column col-12">
    <h3 class="h5 title is-flex-centered">Images</h3>
    <p class=" subtitle is-flex-centered">
      This is the place where you'll upload any images you want included on your website. You know, to make it beautiful! 😊
    </p>
  </div>
  <div class="column col-12">
    <div class="columns">
      <% if current_user.uploads_complete? %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-centered">
            Status: <span class="complete">Complete ✅</span>
          </div>
        </div>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to upload_path(current_user.upload) do %>
              <i class="icon icon-photo"></i> See Your Uploaded Images
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="status is-flex-centered">
            Status: <span class="in-progress">Needs work</span> 🚧
          </div>  
        </div>  
        <div class="column col-5 col-md-12 col-mx-auto">
          <div class="row-link">
            <%= link_to edit_upload_path(current_user.upload) do %>
              <i class="icon icon-upload"></i> Upload Images
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>  